// ─── Content Provenance Classification ─────────────────────────────────────────
// Defines the 4-tier provenance taxonomy for SECCION platform transparency.
// Used by ProvenanceBadge, ProvenanceSelector, and auto-detection services.
// ────────────────────────────────────────────────────────────────────────────────

export type ProvenanceLevel =
  | 'genuine'       // 100% human-created
  | 'ai_assisted'   // Human-created with AI enhancement
  | 'ai_generated'  // Fully AI-generated (Replicant content)
  | 'ai_enhanced';  // Human original modified with AI tools

export interface ProvenanceMetadata {
  level: ProvenanceLevel;
  declaredBy: 'creator' | 'platform_auto' | 'admin';
  creatorName?: string;
  creatorConsent?: string;   // ISO timestamp of digital_replica_consent
  toolsUsed?: string[];      // e.g., ['midjourney', 'runway', 'seccion-replicant']
  declaredAt: string;        // ISO timestamp
  autoDetectionResult?: AutoDetectionResult | null;
}

export interface AutoDetectionResult {
  isAiGenerated: boolean;
  confidence: number;        // 0–100
  detectedModel?: string;    // e.g., 'midjourney-v6', 'dall-e-3'
  suggestedLevel: ProvenanceLevel;
  source: 'hive' | 'c2pa' | 'synthid';
  checkedAt: string;         // ISO timestamp
}

// ─── Provenance Tier Definitions ────────────────────────────────────────────────
// Each tier has full descriptions and real-world examples for the upload selector.

export const PROVENANCE_TIERS: Record<
  ProvenanceLevel,
  {
    label: string;
    labelEs: string;
    emoji: string;
    color: string;
    bgClass: string;
    borderClass: string;
    textClass: string;
    shortDesc: string;
    shortDescEs: string;
    fullDesc: string;
    fullDescEs: string;
    examples: string;
    examplesEs: string;
  }
> = {
  genuine: {
    label: '100% Genuine',
    labelEs: '100% Genuino',
    emoji: '✓',
    color: 'emerald',
    bgClass: 'bg-emerald-500/10',
    borderClass: 'border-emerald-500/20',
    textClass: 'text-emerald-400',
    shortDesc: 'Fully human-created',
    shortDescEs: 'Creado 100% por humano',
    fullDesc:
      'This content was created entirely by the creator without any AI generation tools. ' +
      'Photos are taken by camera, videos are recorded live, and text is written by the creator personally.',
    fullDescEs:
      'Este contenido fue creado enteramente por el creador sin herramientas de generación IA. ' +
      'Las fotos fueron tomadas con cámara, los videos grabados en vivo y el texto escrito personalmente.',
    examples: 'Selfies, filmed videos, handwritten captions, live recordings',
    examplesEs: 'Selfies, videos filmados, subtítulos escritos a mano, grabaciones en vivo',
  },
  ai_assisted: {
    label: 'AI-Assisted',
    labelEs: 'Asistido por IA',
    emoji: '⚡',
    color: 'blue',
    bgClass: 'bg-blue-500/10',
    borderClass: 'border-blue-500/20',
    textClass: 'text-blue-400',
    shortDesc: 'Human-created, AI-enhanced',
    shortDescEs: 'Creado por humano, mejorado por IA',
    fullDesc:
      'The core content was created by the creator, but AI tools were used to enhance it. ' +
      'This includes AI-powered filters, background removal, auto-captioning, color grading, or grammar correction.',
    fullDescEs:
      'El contenido base fue creado por el creador, pero se usaron herramientas de IA para mejorarlo. ' +
      'Incluye filtros con IA, eliminación de fondo, subtitulado automático, corrección de color o gramática.',
    examples: 'Photos with AI filters, AI-captioned videos, AI-corrected text, auto-enhanced lighting',
    examplesEs: 'Fotos con filtros IA, videos con subtítulos IA, texto corregido por IA, iluminación mejorada',
  },
  ai_generated: {
    label: '100% Replicant',
    labelEs: '100% Replicant',
    emoji: '✦',
    color: 'violet',
    bgClass: 'bg-violet-500/10',
    borderClass: 'border-violet-500/20',
    textClass: 'text-violet-400',
    shortDesc: "Fully generated by the creator's Replicant",
    shortDescEs: 'Generado completamente por el Replicant del creador',
    fullDesc:
      'This content was entirely generated by AI on behalf of the creator. ' +
      "The creator authorized their Replicant to produce this using their trained voice, style, and likeness. " +
      'No human-captured original media is present.',
    fullDescEs:
      'Este contenido fue generado completamente por IA en nombre del creador. ' +
      'El creador autorizó a su Replicant para producirlo usando su voz, estilo e imagen entrenados. ' +
      'No hay medios originales capturados por humano.',
    examples: 'AI-generated images, Replicant-written messages, AI voice recordings, synthetic avatars',
    examplesEs: 'Imágenes generadas por IA, mensajes escritos por Replicant, grabaciones de voz IA, avatares sintéticos',
  },
  ai_enhanced: {
    label: 'AI-Enhanced',
    labelEs: 'Mejorado por IA',
    emoji: '🔮',
    color: 'amber',
    bgClass: 'bg-amber-500/10',
    borderClass: 'border-amber-500/20',
    textClass: 'text-amber-400',
    shortDesc: 'Original content modified by AI',
    shortDescEs: 'Contenido original modificado por IA',
    fullDesc:
      'The creator started with real, original content but used AI to significantly modify it beyond simple filters. ' +
      'This includes AI face-tuning, body modification, AI background replacement, or AI-powered video editing that alters the scene.',
    fullDescEs:
      'El creador comenzó con contenido original real pero usó IA para modificarlo significativamente más allá de filtros simples. ' +
      'Incluye retoque facial IA, modificación corporal, reemplazo de fondo IA o edición de video con IA que altera la escena.',
    examples: 'AI face-tuned photos, AI background swaps, AI video effects, deepfake-style modifications on own content',
    examplesEs: 'Fotos retocadas por IA, cambios de fondo IA, efectos de video IA, modificaciones tipo deepfake en contenido propio',
  },
};

// ─── Utility Functions ──────────────────────────────────────────────────────────

/** Returns the ordered list of provenance levels for UI selectors */
export const PROVENANCE_ORDER: ProvenanceLevel[] = [
  'genuine',
  'ai_assisted',
  'ai_enhanced',
  'ai_generated',
];

/** Get the display config for a given provenance level */
export function getProvenanceTier(level: ProvenanceLevel) {
  return PROVENANCE_TIERS[level] ?? PROVENANCE_TIERS.genuine;
}

/** Check if a provenance level requires digital_replica_consent */
export function requiresReplicantConsent(level: ProvenanceLevel): boolean {
  return level === 'ai_generated';
}

/** Build a ProvenanceMetadata object for a new content upload */
export function createProvenanceMetadata(
  level: ProvenanceLevel,
  creatorName?: string,
  consentTimestamp?: string | null,
  toolsUsed?: string[],
): ProvenanceMetadata {
  return {
    level,
    declaredBy: 'creator',
    creatorName,
    creatorConsent: consentTimestamp ?? undefined,
    toolsUsed,
    declaredAt: new Date().toISOString(),
    autoDetectionResult: null,
  };
}

/**
 * Determines the suggested provenance level from auto-detection confidence.
 * - > 90% confidence → ai_generated
 * - 50–90% confidence → ai_assisted
 * - < 50% confidence → trust creator's self-declaration
 */
export function suggestProvenanceFromDetection(confidence: number): ProvenanceLevel | null {
  if (confidence > 90) return 'ai_generated';
  if (confidence >= 50) return 'ai_assisted';
  return null; // trust self-declaration
}
